apiVersion: v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: nginx 
    template: 
      metadata: 
        labels: 
          app: nginx 
       spec: 
         containers:
         - name: nginx
           image: nginx:1.19.1
           ports:
           - containerPort: 80
         volumeMounts:
         - name: config-volume
           mountPath: /etc/nginx
         - name: htpasswd-volume
           mountPath: /etc/nginx/conf
         volumes:
         - name: config-volume
           configMap:
             name: nginx-config
         - name: htpasswd-volume
           secret:
             secretName: nginx-htpasswd
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - port: 80
